site_name: github-actions-sandbox
site_url: https://nifty-swartz-0c82fb.netlify.app
site_description: Render reproducible examples of Python code for sharing.
repo_url: https://github.com/jayqi/github-actions-sandbox
theme:
  name: material

nav:
  - Home: "index.md"

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - toc:
      permalink: true
      toc_depth: 3
  - mdx_truly_sane_lists:

plugins:
  - search:

extra:
  version:
    provider: mike
