name: docs-main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and publish new dev docs
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: mike
        working-directory: docs
        run: |
          mike deploy --push dev
