name: docs-release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and publish new release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check that versions match
        run: |
          echo "${{ github.event.release.tag_name }}"
          PACKAGE_VERSION=$(cat docs/docs/version.md)
          echo $PACKAGE_VERSION
          [ ${{ github.event.release.tag_name }} == "v$PACKAGE_VERSION" ] || { exit 1; }

      - name: mike
        working-directory: docs
        run: |
          git config --global user.name GitHub Actions
          git config --global user.email noreply@github.com
          mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
