name: tests

on:
  workflow_dispatch:

jobs:
  install:
    name: "Install LightGBM from PyPI on macOS"
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print system information
        run: |
          sw_vers

      - name: Install LightGBM with pip
        run: |
          python -m pip install --upgrade pip
          pip install lightgbm

  install-source:
    name: "Install LightGBM source from PyPI on macOS"
    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Print system information
        run: |
          sw_vers

      - name: Install LightGBM with pip
        run: |
          python -m pip install --upgrade pip
          pip install lightgbm --no-binary lightgbm
