name: pip-cache

on:
  pull_request:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade

      - name: Attach Python site-packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ matrix.os }}-py${{ matrix.python-version }}


      - name: Lint package
        run: |
          echo "Your code is alright."
          # echo "Your code stinks."
          # exit 1

  tests:
    name: "Tests: ${{ matrix.os }}, Python ${{ matrix.python-version }}"
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade

      - name: Attach Python site-packages cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ matrix.os }}-py${{ matrix.python-version }}

      - name: Run tests
        run: |
          echo "Tests passed."
