name: sequence-first

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Echo
          run: |
            echo "Running step"
