name: test-failed-build-issue-action-main

on:
  workflow_dispatch:

jobs:
  failing-test:
    name: Failing Test
    runs-on: ubuntu-latest
    steps:
      - name: Run failing test
        run: |
          bash -c 'exit 1'

  notify:
    name: Notify failed build
    needs: failing-test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: jayqi/failed-build-issue-action
          ref: main

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
