name: test-failed-build-issue-action-v1

on:
  workflow_dispatch:

jobs:
  failing-test:
    name: Failing Test
    runs-on: ubuntu-latest
    steps:
      - name: Run failing test
        run: |
          bash -c 'exit 1'

  notify:
    name: Notify failed build
    needs: failing-test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
